### ISSUE TITLE
dev-master 34208ee

### ISSUE THREAD

**Issue by Jok3r11of** [Pseudoagentur/soa-sentinel#39]
Just Updated,  comments on new features:
```
1. 'sidebar_mini'		=> true, Doesn,t work and also 2 title are shown mini+normal
2. control.js:15 Uncaught TypeError: Cannot read property 'locale' of undefined
4. init.js:9 Uncaught TypeError: Cannot read property 'lang' of undefined
3. domain/admin/assets/lang Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
And because of this JS erros TableAsync() doesnt load.
Thank you)

**Comment by Jok3r11of** [comment]
Any idea when it will work again?)))

**Comment by noxify** [comment]
currently I do some tests to solve some problems - I will check this.

**Comment by noxify** [comment]
I have tested it with a new installation with Laravel 5.1.16 in Chrome Browser:

```1. 'sidebar_mini'       => true, Doesn,t work and also 2 title are shown mini+normal```
In my tests it's working fine.
In case that the sidebar is minimized, I see only the value from the config value `title-mini`.

```3. domain/admin/assets/lang Failed to load resource: the server responded with a status of 500 (Internal Server Error)```

fixed in the develop branch

I think 2 and 4 are errors based on 3.

Maybe you should also run `php artisan vendor:publish --force` after `composer update`.

**Comment by Jok3r11of** [comment]
Thank you a lot, ```php artisan vendor:publish --force``` worked for mini-sidebar, I did it before on composer update, but I think --force was required.

For others wating for master branch)))) 
Thank you again.

**Comment by noxify** [comment]
Can we close this?

**Comment by Jok3r11of** [comment]
@noxify Sure, if others are also fixed in develop branch)))
Thank you

**Comment by noxify** [comment]
I was only able to reproduce 1. and 3. based on the given information :)

The 2. and 4. are exists, please send me the exact steps to reproduce.
Otherwise we will close this issue - I have fixed also some issues which we implement with the merge *dum di dum* :D

**Comment by Jok3r11of** [comment]
@noxify 
I can give only this info
```control.js:15 Uncaught TypeError: Cannot read property 'locale' of undefined```
This Error on ```domain.com/admin``` doesn't exist, but whe I go to ```domain.com/admin/model```
The can be seen in ```console```
For Model show I use ```datatablesAsync();```

**Comment by Jok3r11of** [comment]
@noxify 
```{form.submit();}});});bootbox.setDefaults('locale',window.admin.locale);});```
Here

**Comment by Jok3r11of** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3294939/9694616/ff564ec8-5362-11e5-86d7-e6ede628bf76.png)
And this on creating new Item
```/admin/model/create```

**Comment by noxify** [comment]
Hi,

i have tested it with a fresh laravel installation with `"pseudoagentur/soa-sentinel" : "dev-develop"`.
Everything is working fine in my case.

My Admin Model is the `app/Admin/User.php` with the following Content:

```
<?php

\Admin::model('Cartalyst\Sentinel\Users\EloquentUser')->title('Users')->alias('users')->permission("xyz")->display(function ()
{
	$display = AdminDisplay::datatablesAsync();
	$display->columns([
		Column::checkbox(),
		Column::string('id')->label('#'),
		Column::string('name')->label('Name'),
		Column::string('email')->label('Email'),
	]);
	return $display;
})->createAndEdit(function ()
{
	$form = AdminForm::form();
	$form->items([
		FormItem::text('email', 'Email')->required()->unique(),
	]);
	return $form;
});
```

but there is no error message in the browser console.

In the `config/app.php` the value for `locale` and `fallback_locale` is `en`.
Maybe we have here only a problem with a different language, because some languages are not available or something else.

It would be good if you can give me the following information:

* What is your default language?
* Are you using the master or the develop branch?
* Can you paste (maybe as gist?) your admin model?

Thanks.

**Comment by Jok3r11of** [comment]
What is your default language? - I tried both ru and en
master branch
I close it because it all fixed in develop

**Comment by noxify** [comment]
perfect - thanks a lot for your feedback :)
