### ISSUE TITLE
CKEditor translatable bug

### ISSUE THREAD

**Issue by EugeneTelyatnik** [Pseudoagentur/soa-sentinel#87]
Hi. Thanks for the great admin.

CKEditor is not working with translatable module.

In ckeditor.blade.php I found small bug:
```html
<textarea class="ckeditor" name="{{ $name }}">{!! $value !!}</textarea>
```
but must be:
```html
<textarea class="ckeditor" name="@if($lang){{ $lang }}{{'_'}}@endif{{ $name }}">{!! $value !!}</textarea>
```

P.S.
TinyMCE is not working too.

**Comment by noxify** [comment]
Thanks @EugeneTelyatnik - We will fix it as soon as possible.

**Comment by bihlmaierh** [comment]
Hello @EugeneTelyatnik ,

I will integrate your ckeditor bugfix in our system.

TinyMCE has this bug currently not, because there it is included (see https://github.com/Pseudoagentur/soa-sentinel/blob/release/3.0.1/src/views/default/formitem/tinymce.blade.php)

But addional you need to add manually the mce_selector.

See docs: http://docs.pseudoagentur.de/soa-sentinel/master/field/tinymce

Example: `->mce_selector($lang . '_tinymce)`

Can u verfiy your tinymce view file and these explanations ?

**Comment by EugeneTelyatnik** [comment]
Hi @bihlmaierh ,
Thanks for your tips. Works fine.

**Comment by bihlmaierh** [comment]
Closed.
